---
#TODO: checagens de sanidade. Verificar se o sistema operacional é suportado.
# - name: checar se `"ansible_distribution": "Ubuntu"`
# - name: checar se `ansible_distribution_version": "16.04"`
# - name: checar se `"ansible_distribution_release": "xenial"`

- name: atualizar cache apt
  apt:
    update_cache: yes
    cache_valid_time: "{{ ___docker___cache_valid_time }}"

- name: instalar pacotes pré-requeridos
  apt:
    name: "{{ ___docker___required_packages }}"

- name: adicionar chave GPG
  apt_key:
    url: "{{ ___docker___repo_gpg_key_url }}"

- name: adiciona repositório apt do docker
  apt_repository:
    repo: "{{ ___docker___repo }}"
  register: docker_apt_repo_add

- name: atualiza cache apt quando repositório adicionado
  apt:
    update_cache: yes
  when: docker_apt_repo_add.changed

- name: instala pacotes docker
  apt:
    name: "{{ ___docker___pkgs }}"

- block:
    - name: baixar docker-compose
      get_url:
        url: "{{ ___docker___compose_url }}"
        dest: "{{ ___docker___compose_install_dir }}/\
          {{ ___docker___compose_output_file }}"
        mode: 0750
    - name: baixar completion
      get_url:
        url: "{{ ___docker___compose_bash_completion_url }}"
        dest: "{{ ___docker___compose_bash_completion_install_dir }}/\
          {{ ___docker___compose_bash_completion_output_file }}"
        mode: 0644
  when: docker___compose_install
  tags: docker_compose

- name: instalar Pip
  apt:
    name: python-pip

- name: instalar biblioteca python para docker
  pip:
    name: docker