---
#TODO: checagens de sanidade. Verificar se o sistema operacional é suportado.
# - name: checar se `"ansible_distribution": "Ubuntu"`
# - name: checar se `ansible_distribution_version": "16.04"`
# - name: checar se `"ansible_distribution_release": "xenial"`

- name: atualizar cache apt
  apt:
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"

- name: instalar pacotes pré-requeridos
  apt:
    name: "{{ required_packages }}"

- name: adicionar chave GPG
  apt_key:
    url: "{{ repo_gpg_key_url }}"

- name: adiciona repositório apt do docker
  apt_repository:
    repo: "{{ docker_repo }}"
  register: docker_apt_repo_add

- name: atualiza cache apt quando repositório adicionado
  apt:
    update_cache: yes
  when: docker_apt_repo_add.changed

- name: instala pacote docker
  apt:
    name: "{{ docker_pkg }}"

- name: bloco docker-compose
  block:
    - name: baixar docker-compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: "{{ docker_compose_install_dir }}/{{ docker_compose_output_file }}"
        mode: 0750
    - name: baixar completion
      get_url:
        url: "{{ docker_compose_bash_completion_url }}"
        dest: "{{ docker_compose_bash_completion_install_dir }}/{{ docker_compose_bash_completion_output_file }}"
        mode: 0644
  tags: docker_compose

- name: instalar Pip
  apt:
    name: python-pip

- name: instalar biblioteca python para docker
  pip:
    name: docker